### ISSUE TITLE
warning à la désactivation

### ISSUE THREAD

**Issue by brol** [JcDenis/improve#10]
salut,
quand je désactive le plugin, j'ai une belle erreur en bas de page (page des plugins) : 
2.25-dev-r20230112.1548
`<html><body>
<font size="1">

Fatal error: Uncaught Error: Class "Dotclear\Plugin\improve\Uninstall"  not found in  F:\wamp64\www\labodc2\all-blogs\plugins\improve\_uninstall.php on line 15
--

1 | 0.0001 | 361328 | {main}(  ) | ...\plugins.php:0
2 | 0.2190 | 1867456 | adminPlugins::render(  ) | ...\plugins.php:313
3 | 0.2596 | 2758200 | dcCore->callBehavior( $behavior = 'pluginsToolsTabsV2' ) | ...\plugins.php:260
4 | 0.2596 | 2758200 | dcModules->{closure:F:\wamp64\www\labodc2\all-blogs\plugins\dcAdvancedCleaner\_admin.php:40-143}(  ) | ...\class.dc.core.php:794
5 | 0.2600 | 2765136 | dcUninstaller->loadModules( $path = 'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../plugins;F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins' ) | ...\_admin.php:50
6 | 0.2658 | 2784896 | dcUninstaller->loadModule( $root = 'F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins//improve' ) | ...\class.dc.uninstaller.php:100
7 | 0.2659 | 2785712 | require( 'F:\wamp64\www\labodc2\all-blogs\plugins\improve\_uninstall.php )

</font>
</body>
</html>`

**Comment by JcDenis** [comment]
Tiens, il manque un slash dans le relevé d'erreur ?!

**Comment by brol** [comment]
hein ?
sinon, en fait source de la page, j'ai ça : 
'<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Class "Dotclear\Plugin\improve\Uninstall" not found in F:\wamp64\www\labodc2\all-blogs\plugins\improve\_uninstall.php on line <i>15</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Class "Dotclear\Plugin\improve\Uninstall" not found in F:\wamp64\www\labodc2\all-blogs\plugins\improve\_uninstall.php on line <i>15</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>361328</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='F:\wamp64\www\labodc2\dotclear\admin\plugins.php' bgcolor='#eeeeec'>...\plugins.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.2285</td><td bgcolor='#eeeeec' align='right'>1980200</td><td bgcolor='#eeeeec'>adminPlugins::render(  )</td><td title='F:\wamp64\www\labodc2\dotclear\admin\plugins.php' bgcolor='#eeeeec'>...\plugins.php<b>:</b>313</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.3048</td><td bgcolor='#eeeeec' align='right'>2820872</td><td bgcolor='#eeeeec'>dcCore->callBehavior( <span>$behavior = </span><span>&#39;pluginsToolsTabsV2&#39;</span> )</td><td title='F:\wamp64\www\labodc2\dotclear\admin\plugins.php' bgcolor='#eeeeec'>...\plugins.php<b>:</b>260</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.3049</td><td bgcolor='#eeeeec' align='right'>2820872</td><td bgcolor='#eeeeec'>dcModules->{closure:F:\wamp64\www\labodc2\all-blogs\plugins\dcAdvancedCleaner\_admin.php:40-143}(  )</td><td title='F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.core.php' bgcolor='#eeeeec'>...\class.dc.core.php<b>:</b>794</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.3054</td><td bgcolor='#eeeeec' align='right'>2827808</td><td bgcolor='#eeeeec'>dcUninstaller->loadModules( <span>$path = </span><span>&#39;F:\\wamp64\\www\\labodc2\\dotclear\\inc/../plugins;F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins&#39;</span> )</td><td title='F:\wamp64\www\labodc2\all-blogs\plugins\dcAdvancedCleaner\_admin.php' bgcolor='#eeeeec'>...\_admin.php<b>:</b>50</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.3114</td><td bgcolor='#eeeeec' align='right'>2847568</td><td bgcolor='#eeeeec'>dcUninstaller->loadModule( <span>$root = </span><span>&#39;F:\\wamp64\\www\\labodc2\\dotclear\\inc/../../all-blogs/plugins//improve&#39;</span> )</td><td title='F:\wamp64\www\labodc2\all-blogs\plugins\dcAdvancedCleaner\inc\class.dc.uninstaller.php' bgcolor='#eeeeec'>...\class.dc.uninstaller.php<b>:</b>100</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.3115</td><td bgcolor='#eeeeec' align='right'>2848384</td><td bgcolor='#eeeeec'>require( <font color='#00bb00'>'F:\wamp64\www\labodc2\all-blogs\plugins\improve\_uninstall.php</font> )</td><td title='F:\wamp64\www\labodc2\all-blogs\plugins\dcAdvancedCleaner\inc\class.dc.uninstaller.php' bgcolor='#eeeeec'>...\class.dc.uninstaller.php<b>:</b>126</td></tr>
</table></font>'
