### ISSUE TITLE
\inc\module\dcdeprecated\dc2.21.php

### ISSUE THREAD

**Issue by brol** [JcDenis/improve#11]
salut

ligne 18, c'est deux fois la même chose

**Comment by JcDenis** [comment]
oups un peu brouillon tout ça !

**Comment by brol** [comment]
y a que moi qui te remonte des trucs ou quoi ?

**Comment by JcDenis** [comment]
Non, mais tu es au top en ce moment !
En tout cas n'hésite pas, et même des trucs qui peuvent paraitre bête. C'est pratique pour moi ici.

**Comment by brol** [comment]
un truc un peu bizarre alors, peut-être voulu ?
même les ressources non actives sont listées dans improve. curieux.

**Comment by JcDenis** [comment]
Dans mes souvenirs, c'est un choix voulu: pourvoir désactiver un plugin, le corriger et le réactiver après.

**Comment by JcDenis** [comment]
Pour le ticket, je ne vois pas deux fois la même ligne ?

A savoir qu'il y a qu'il y a plusieurs behaviors qui ont changé de fonctionnement, et du coup dorénavant, il faut utilise une méthode commune.

**Comment by brol** [comment]
ce n'est pas une ligne répétée deux fois mais sur la ligne 18 tu as deux fois le même behavior.
['adminCommentsActionsCombo', 'adminCommentsActionsCombo', 'adminCommentsActionsCombo', '2.21', ''],
il me semble que le dernier ne devrait pas être adminCommentsActionsCombo

**Comment by JcDenis** [comment]
Ah ok, je n'avais pas compris et surtout pas ouvert les yeux…
