### ISSUE TITLE
Erreur de lien dans le fichier dcstore.xml pour la version 1.4

### ISSUE THREAD

**Issue by Gvx-** [JcDenis/improve#12]
Le fichier `dcstore.xml` indique une version 1.4 dont l'archive est:
`https://gitea.dotclear.watch/JcDenis/improve/releases/download/v1.4/plugin-improve.zip`
hors le bon lien est:
[https://git.dotclear.watch/JcDenis/improve/releases/download/v1.4/plugin-improve.zip](https://git.dotclear.watch/JcDenis/improve/releases/download/v1.4/plugin-improve.zip)

**Comment by JcDenis** [comment]
Effectivement il n'est pas à jour (je suis en train de changer de serveur)
