### ISSUE TITLE
Version 0.7 non compatible avec PHP < 8.0

### ISSUE THREAD

**Issue by Gvx-** [JcDenis/improve#5]
Après mise a jour de V0.6 a V0.7 j'obtiens cette erreur:

`Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in C:\wamp64\www\dc2-plugins\improve\inc\class.improve.php on line 298
`

Cela est du a l'utilisation de la déclaration de [type union](https://www.php.net/manual/fr/language.types.declarations.php#language.types.declarations.mixed) disponible seulement a partir de PHP 8.0

**Comment by JcDenis** [comment]
exact !
je vais tenter de redescendre. 
Merci du retour.
