### ISSUE TITLE
Action : Dépréciés de Dotclear

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/improve#8]
Visiblement un petit problème de faux-positif sur un plugin, a11yConfig, fichier \_admin.php qui m'indique :

> Possible utilisation du déprécié "adminPreferencesForm", vous devriez utiliser "adminPreferencesFormV2" à la place depuis Dotclear 2.24.

Or j'utilise bien la V2 du behavior : [https://github.com/franck-paul/a11yConfig/blob/b2436d4415a3899cdfa55edb49d58647eed8a7f8/_admin.php#L176](https://github.com/franck-paul/a11yConfig/blob/b2436d4415a3899cdfa55edb49d58647eed8a7f8/_admin.php#L176)

👍 Bien vu le lien vers le billet d'adaptation chez moi ;-)

**Comment by JcDenis** [comment]
Je recherche en rexepx simmple du coup il trouve le second adminPreferencesForm (qui est ta methode perso) je ne sais pas trop comment faire autrement sans faire une usine à gaz :/ Si tu as une idée.

Du coup chez moi j'ai modifié également le nom des methods des plugins.

**Comment by franck-paul** [comment]
Je vais voir si je trouve une regexp qui convient ;-)

**Comment by franck-paul** [comment]
Bon t'as raison, c'est un peu too much de mettre en place une (grosse) regexp de la mort qui tue pour si peu :-)

**Comment by JcDenis** [comment]
Ou alors travailler en asynchrone...

**Comment by franck-paul** [comment]
Ou alors utiliser Rector voire PHPStan pour faire de l'analyse syntaxique et détecter les deprecated non détectés en standard :-p

**Comment by JcDenis** [comment]
feu !

PS: Je te laisse faire hein

**Comment by franck-paul** [comment]
Ouais, je te dis dès que c'est prêt… :-p
